### ISSUE TITLE
Crash if adapter is empty

### ISSUE THREAD

**Issue by okaymak** [LittleMango/StackLayoutManager#2]
```
java.lang.IndexOutOfBoundsException: Invalid item position -1(-1). Item count:0 
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5779)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at com.littlemango.stacklayoutmanager.StackLayoutManager.loadItemView(StackLayoutManager.kt:358)
        at com.littlemango.stacklayoutmanager.StackLayoutManager.onLayoutChildren(StackLayoutManager.kt:289)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
```

**Comment by LittleMango** [comment]
Had fixed in version 1.0.3 thx @okaymak.
