### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by DongjingZhong** [LittleMango/StackLayoutManager#21]
Hi friend ,I like your project ,but I got this issue ,could you please take a look ?Thank you so much
` Process: com.gearsrun.stackviewapplication, PID: 18291
    java.lang.ArithmeticException: divide by zero
        at com.gearsrun.stackviewapplication.stacklayoutmanager.DefaultLayout.getFirstVisibleItemTop(DefaultLayout.kt:66)
        at com.gearsrun.stackviewapplication.stacklayoutmanager.DefaultLayout.doLayout(DefaultLayout.kt:32)
        at com.gearsrun.stackviewapplication.stacklayoutmanager.StackLayoutManager.loadItemView(StackLayoutManager.kt:374)
        at com.gearsrun.stackviewapplication.stacklayoutmanager.StackLayoutManager.onLayoutChildren(StackLayoutManager.kt:298)`

**Comment by shahzaibkhan471** [comment]
same issue

**Comment by aayush0208** [comment]
yeah, same issues happens when recyclerview height is set to wrap_content

**Comment by nicodiansk** [comment]
Set the ReciclerView width to match_parent and you are good to go. Wrap it into a Relative layout if needed.
